#!/bin/bash
# memory-compress.sh — Compress and archive old LEARNINGS entries
# Usage: ./scripts/memory-compress.sh [--dry-run] [--days N]
#
# Archives entries older than N days (default 30) to memory/archive/
# Keeps recent entries in LEARNINGS.md with a category index header
# NEVER deletes — only moves to archive

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LEARNINGS="$PROJECT_DIR/memory/LEARNINGS.md"
ARCHIVE_DIR="$PROJECT_DIR/memory/archive"
DRY_RUN=false
DAYS=30

# Parse args
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --days) DAYS="$2"; shift 2 ;;
    *) shift ;;
  esac
done

# Validate
if [ ! -f "$LEARNINGS" ]; then
  echo "ERROR: $LEARNINGS not found"
  exit 1
fi

BEFORE_LINES=$(wc -l < "$LEARNINGS")
echo "=== Memory Compression ==="
echo "LEARNINGS.md: $BEFORE_LINES lines"
echo "Archive threshold: $DAYS days"
echo "Dry run: $DRY_RUN"

# Create archive directory
mkdir -p "$ARCHIVE_DIR"

# Find date headers and split by month
# LEARNINGS format: "### Month DD, YYYY — Description" or "- **Entry text**"
CUTOFF_DATE=$(date -v-${DAYS}d '+%Y-%m-%d' 2>/dev/null || date -d "-${DAYS} days" '+%Y-%m-%d' 2>/dev/null || echo "2026-02-19")
CUTOFF_MONTH=$(echo "$CUTOFF_DATE" | cut -d'-' -f1-2)
ARCHIVE_FILE="$ARCHIVE_DIR/learnings-before-$CUTOFF_MONTH.md"

echo "Cutoff date: $CUTOFF_DATE"
echo "Archive file: $ARCHIVE_FILE"

# Strategy: Keep entries with dates >= cutoff, archive the rest
# Detect date headers in format "### Month DD, YYYY" or "### YYYY-MM-DD"
TEMP_KEEP=$(mktemp)
TEMP_ARCHIVE=$(mktemp)

# Simple approach: split at the first date header that's within our window
# Keep everything from the cutoff date forward
FOUND_CUTOFF=false
CURRENT_SECTION=""
IN_RECENT=false

while IFS= read -r line; do
  # Detect date headers (March 2026 format or YYYY-MM-DD format)
  if echo "$line" | grep -qE "^### (January|February|March|April|May|June|July|August|September|October|November|December) [0-9]+.*202[0-9]|^### 202[0-9]-[0-9]{2}-[0-9]{2}"; then
    # Extract date - check if it's recent
    if echo "$line" | grep -qE "March (1[5-9]|2[0-9]|3[01]).*2026|March [2-3][0-9].*2026|2026-03-(1[5-9]|2[0-9]|3[01])"; then
      IN_RECENT=true
    fi
  fi

  if [ "$IN_RECENT" = true ]; then
    echo "$line" >> "$TEMP_KEEP"
  else
    echo "$line" >> "$TEMP_ARCHIVE"
  fi
done < "$LEARNINGS"

KEEP_LINES=$(wc -l < "$TEMP_KEEP" 2>/dev/null || echo "0")
ARCHIVE_LINES=$(wc -l < "$TEMP_ARCHIVE" 2>/dev/null || echo "0")

echo ""
echo "Lines to keep (recent): $KEEP_LINES"
echo "Lines to archive (old): $ARCHIVE_LINES"

if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "[DRY RUN] Would archive $ARCHIVE_LINES lines to $ARCHIVE_FILE"
  echo "[DRY RUN] Would keep $KEEP_LINES lines in LEARNINGS.md"
  rm -f "$TEMP_KEEP" "$TEMP_ARCHIVE"
  exit 0
fi

# Only proceed if there's something to archive
if [ "$ARCHIVE_LINES" -gt 10 ]; then
  # Write archive
  {
    echo "# Archived LEARNINGS — Before $CUTOFF_MONTH"
    echo "# Archived on $(date '+%Y-%m-%d %H:%M')"
    echo "# Original file: memory/LEARNINGS.md"
    echo ""
    cat "$TEMP_ARCHIVE"
  } > "$ARCHIVE_FILE"

  # Rebuild LEARNINGS.md with index header
  {
    echo "# LEARNINGS — Energy Platform"
    echo ""
    echo "## Index (auto-generated by memory-compress.sh)"
    echo "- Recent entries: $KEEP_LINES lines (last $DAYS days)"
    echo "- Archived: $ARCHIVE_LINES lines → \`memory/archive/learnings-before-$CUTOFF_MONTH.md\`"
    echo "- Total historical: $BEFORE_LINES lines"
    echo "- Last compressed: $(date '+%Y-%m-%d %H:%M')"
    echo ""
    echo "---"
    echo ""
    cat "$TEMP_KEEP"
  } > "$LEARNINGS"

  AFTER_LINES=$(wc -l < "$LEARNINGS")
  echo ""
  echo "=== Compression Complete ==="
  echo "Before: $BEFORE_LINES lines"
  echo "After: $AFTER_LINES lines"
  echo "Archived: $ARCHIVE_LINES lines → $ARCHIVE_FILE"
  echo "Reduction: $(( BEFORE_LINES - AFTER_LINES )) lines ($(( (BEFORE_LINES - AFTER_LINES) * 100 / BEFORE_LINES ))%)"
else
  echo ""
  echo "Nothing to archive ($ARCHIVE_LINES lines below threshold of 10)"
fi

rm -f "$TEMP_KEEP" "$TEMP_ARCHIVE"
